---
title: "Analysis Pilot 3"
output: 
  html_document: 
    keep_md: yes
---

```{r packages, message=FALSE}
library(tidyverse)     # create plots with ggplot, manipulate data, etc.
library(broom.mixed)   # convert regression models into nice tables
library(modelsummary)  # combine multiple regression models into a single table
library(lme4)          # model specification / estimation 
library(lmerTest)      # provides p-values in the output
library(ggpubr)        # stile feature of ggplot
library(gghalves)      # do special plots in ggplot
library(kableExtra)    # for tables
```

## Import data
```{r import, message=FALSE}
d <- read_csv("./data/cleaned.csv")
```

```{r}
# overall
d %>% 
  group_by(impressiveness) %>% 
  summarise(across(c(impressed, learn, know, competence, trust), 
                   list(mean = ~mean(.)), 
                   .names = "{col}_{fn}")) %>% 
  mutate_if(is.numeric, ~round(.x, digits = 2)) %>% 
  kable() %>% 
  kable_classic(full_width = F)
```

```{r}
# by discipline
d %>% 
  group_by(discipline, impressiveness) %>% 
  summarise(across(c(impressed, learn, competence, trust), 
                   list(mean = ~mean(.)), 
                   .names = "{col}_{fn}")) %>% 
  mutate_if(is.numeric, ~round(.x, digits = 2)) %>% 
  kable() %>% 
  kable_classic(full_width = F)
```

```{r}
cor(d$know, d$trust)
```


```{r}
plot_data <- d %>% 
  group_by(know, trust) %>% 
  summarise(n = n())

# Plot as a tile plot
ggplot(plot_data, aes(x = know, y = trust, fill = n)) +
  geom_tile() +  # Add black border around tiles for better visibility
  geom_jitter(inherit.aes = FALSE, data = d, aes(x = know, y = trust)) +  # Scatter points within each tile
  scale_fill_viridis_c(option = "plasma") +  # Use Viridis color scale (Plasma)
  scale_x_continuous(breaks = 1:5) +
  scale_y_continuous(breaks = 1:5) +
  labs(x = "Perceived change in knowledge", 
       y = "Perceived change in trust", 
       fill = "Count") +  # Update fill legend title
  theme_minimal() +
  facet_wrap(~impressiveness)
```


