---
title: "Analysis Study 1"
output:
  bookdown::pdf_document2: default
  bookdown::word_document2: default
  bookdown::html_document2:
      keep_md: yes
always_allow_html: true
bibliography: ../references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r packages, message=FALSE, echo=FALSE, include=FALSE}
library(tidyverse)     # create plots with ggplot, manipulate data, etc.
library(broom.mixed)   # convert regression models into nice tables
library(modelsummary)  # combine multiple regression models into a single table
library(lme4)          # model specification / estimation 
library(lmerTest)      # provides p-values in the output
library(ggpubr)        # stile feature of ggplot
library(gghalves)      # do special plots in ggplot
library(kableExtra)    # for tables
library("grid")        # for image plots   
library("gridExtra")   # for image plots
library("png")         # for image plots
library(stargazer)
```

```{r, include=FALSE, message=FALSE}
# read the cleaned long version data set
data <- read_csv("data/cleaned.csv")
```

```{r}
# as table
data %>%
  mutate(knowledge = as.factor(knowledge_avg)) %>%
  group_by(knowledge_avg) %>%
  count() %>%
  ungroup() %>%
  mutate(share = n / sum(n)) %>%
  mutate_if(is.numeric, round, digits = 3)
```

```{r}
# as plot
# Calculate the mean
mean_values <- data %>% 
  group_by(discipline) %>% 
  summarize(knowledge_avg = mean(knowledge_avg, na.rm = TRUE))

ggplot(data, aes(x = knowledge_avg)) +
  geom_bar() + 
  geom_vline(data = mean_values, aes(xintercept = knowledge_avg), color = "red", linetype = "dashed") +
  geom_text(data = mean_values, aes(x = knowledge_avg , y = 11, label = paste("Mean =", round(knowledge_avg , 2))), 
            vjust = -0.5, hjust = 1.2) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0, 10, 1)) +
  labs(x = "Average knowledge score", 
       y = "N") +
  facet_wrap(~discipline)
```

```{r}
# as plot
# Calculate the mean
data %>% 
  group_by(discipline) %>% 
  summarize(n_correct = n_distinct(n_correct))

ggplot(data, aes(x = n_correct)) +
  geom_bar() +
  scale_x_continuous(breaks = seq(0, 5, 1)) +
  scale_y_continuous(breaks = seq(0, 10, 1)) +
  labs(x = "Number of correct answers", 
       y = "N") +
  facet_wrap(~discipline)
```

```{r}
question_data <- data %>% 
  # bring to long format
  pivot_longer(cols = starts_with("knowledge") & !ends_with("avg"), 
               names_to = "question", values_to = "answer") %>% 
  group_by(discipline, question) %>% 
  summarize(avg_answer = mean(answer), 
            n_correct = sum(answer), 
            n = n()) %>% 
  mutate(share_correct = n_correct/n) %>% 
  ungroup()

ggplot(question_data , aes(x = question, y = share_correct)) +
  geom_col() +
  labs(x = "Question", y = "Share of correct answers") +
  coord_flip() +
  facet_wrap(~discipline)
```


